import test from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {accountAllowed,accountSessionAllowed} from '../src/lib/security/account.mjs';
test('global account policy and live session remain authoritative for cached identities',async()=>{
 const db=new PGlite();await db.exec(`CREATE TABLE "user"(id text PRIMARY KEY);CREATE TABLE platform_subject_policy(subject_kind text,subject_id text,state text);CREATE TABLE "session"(id text,user_id text,expires_at timestamptz);INSERT INTO "user" VALUES('active'),('suspended'),('blocked');INSERT INTO platform_subject_policy VALUES('user','suspended','suspended'),('user','blocked','blocked');INSERT INTO "session" VALUES('live','active',now()+interval '1 hour'),('expired','active',now()-interval '1 second'),('foreign','suspended',now()+interval '1 hour');`);
 try{assert.equal(await accountAllowed(db,'active'),true);for(const id of ['suspended','blocked','deleted'])assert.equal(await accountAllowed(db,id),false);assert.equal(await accountSessionAllowed(db,'active','live'),true);for(const id of [undefined,'expired','foreign','revoked'])assert.equal(await accountSessionAllowed(db,'active',id),false);await db.exec('DROP TABLE platform_subject_policy');await assert.rejects(accountAllowed(db,'active'),e=>e.status===503);}finally{await db.close();}
});

test('cached BetterAuth identities are rejected at the production API and handler boundary',async()=>{
 const {readFile}=await import('node:fs/promises');const {createRequire}=await import('node:module');const vm=await import('node:vm');const ts=createRequire(import.meta.url)('typescript');const exports={};vm.runInNewContext(ts.transpileModule(await readFile('src/lib/security/auth-guard.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Response,Headers,URL});
 const db=new PGlite();await db.exec(`CREATE TABLE "user"(id text PRIMARY KEY);CREATE TABLE platform_subject_policy(subject_kind text,subject_id text,state text);CREATE TABLE "session"(id text,user_id text,expires_at timestamptz);INSERT INTO "user" VALUES('member');INSERT INTO "session" VALUES('cached','member',now()+interval '1 hour');`);
 let work=0;const base={api:{getSession:async()=>({user:{id:'member'},session:{id:'cached'}})},handler:async()=>{work++;return new Response('ok');}};const auth=exports.wrapAccountAuth(base,(userId,sessionId)=>accountSessionAllowed(db,userId,sessionId));
 try{assert.equal((await auth.api.getSession()).user.id,'member');await db.exec("INSERT INTO platform_subject_policy VALUES('user','member','suspended')");assert.equal(await auth.api.getSession(),null);assert.equal((await auth.handler(new Request('https://members.axxes.club/api/auth/get-session'))).status,401);assert.equal(work,0);assert.equal((await auth.handler(new Request('https://members.axxes.club/api/auth/sign-out',{method:'POST'}))).status,200);await db.exec('DROP TABLE platform_subject_policy');assert.equal((await auth.handler(new Request('https://members.axxes.club/api/auth/get-session'))).status,503);assert.equal(work,1);}finally{await db.close();}
});
