import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {PGlite} from '@electric-sql/pglite';import {readFile} from 'node:fs/promises';
import {parseWebhook,reserveDelivery,finishDelivery} from '../src/lib/security/webhook.mjs';
const secret='unit-only-webhook-secret';
function request(payload,signed=true){const raw=JSON.stringify(payload);return new Request('https://members.axxes.club/api/integrations/afters/webhook',{method:'POST',headers:{'x-afters-signature':signed?createHmac('sha256',secret).update(raw).digest('hex'):'forged'},body:raw});}
test('missing secret and forged signature never produce a dispatch identity',async()=>{await assert.rejects(parseWebhook(request({}),undefined),e=>e.status===503);await assert.rejects(parseWebhook(request({tenant_id:'tenant'} ,false),secret),e=>e.status===401);});
test('signed webhook canonical tenant cannot be overwritten by its data',async()=>{const event=await parseWebhook(request({event_type:'event.updated',tenant_id:'00000000-0000-4000-8000-000000000001',data:{tenant_id:'foreign'}}),secret);assert.equal(event.tenantId,'00000000-0000-4000-8000-000000000001');assert.equal(event.payload.tenant_id,event.tenantId);});
test('duplicate signed deliveries run only once and failed attempts can be retried',async()=>{
 const db=new PGlite();await db.exec(await readFile(new URL('../db/security-webhook-receipts.sql',import.meta.url),'utf8'));
 try{const results=await Promise.all(Array.from({length:10},()=>reserveDelivery(db,'afters','digest')));assert.equal(results.filter(Boolean).length,1);const lease=results.find(Boolean);await finishDelivery(db,'afters','digest',lease,false);const retry=await reserveDelivery(db,'afters','digest');assert.ok(retry);await finishDelivery(db,'afters','digest',retry,true);assert.equal(await reserveDelivery(db,'afters','digest'),null);}finally{await db.close();}
});

test('an expired delivery cannot finish or delete a newer reservation',async()=>{const db=new PGlite();await db.exec(await readFile(new URL('../db/security-webhook-receipts.sql',import.meta.url),'utf8'));try{const old=await reserveDelivery(db,'afters','lease');await db.exec("UPDATE security_webhook_receipts SET expires_at=now()-interval '1 second'");const current=await reserveDelivery(db,'afters','lease');assert.notEqual(old,current);await finishDelivery(db,'afters','lease',old,false);assert.equal(await reserveDelivery(db,'afters','lease'),null);await finishDelivery(db,'afters','lease',current,true);assert.equal(await reserveDelivery(db,'afters','lease'),null);}finally{await db.close();}});
