import test from 'node:test';
import assert from 'node:assert/strict';
import { CommerceOrders } from '../../src/lib/commerce/orders';
import { fixture,buyer,ticket,product,variant,other,event } from './fixture';
const cart={buyer,items:[{kind:'ticket' as const,id:ticket,quantity:2}]};
test('server pricing overrides client amount and creates canonical order',async()=>{const {db,pool}=await fixture();try{const s=new CommerceOrders(pool,{receiptSecret:"fixture-receipt-secret-at-least-24-chars"});const r=await s.createOrder('gangstarz',{...cart,amount:1},'price-check-key');assert.equal(r.amount,5000);assert.equal((await db.query<{n:number;quantity:number;quantity_reserved:number}>('SELECT count(*)::int n FROM orders')).rows[0].n,1);assert.equal((await db.query<{n:number;quantity:number;quantity_reserved:number}>('SELECT quantity_reserved FROM ticket_types')).rows[0].quantity_reserved,2)}finally{await db.close()}});
test('duplicate checkout reserves once and preserves receipt capability',async()=>{const {db,pool}=await fixture();try{const s=new CommerceOrders(pool,{receiptSecret:"fixture-receipt-secret-at-least-24-chars"});const a=await s.createOrder('gangstarz',cart,'repeat-key-1234');const b=await s.createOrder('gangstarz',cart,'repeat-key-1234');assert.equal(a.id,b.id);assert.equal(a.token,b.token);assert.equal((await db.query<{n:number;quantity:number;quantity_reserved:number}>('SELECT quantity_reserved FROM ticket_types')).rows[0].quantity_reserved,2)}finally{await db.close()}});
test('changed retry payload conflicts',async()=>{const {db,pool}=await fixture();try{const s=new CommerceOrders(pool,{receiptSecret:"fixture-receipt-secret-at-least-24-chars"});await s.createOrder('gangstarz',cart,'repeat-key-1234');await assert.rejects(s.createOrder('gangstarz',{...cart,items:[{kind:'ticket',id:ticket,quantity:3}]},'repeat-key-1234'),/different|conflict/i)}finally{await db.close()}});
test('foreign tenant product cannot be purchased',async()=>{const {db,pool}=await fixture();try{await db.query<{n:number;quantity:number;quantity_reserved:number}>('UPDATE products SET tenant_id=$1 WHERE id=$2',[other,product]);const s=new CommerceOrders(pool,{receiptSecret:"fixture-receipt-secret-at-least-24-chars"});await assert.rejects(s.createOrder('gangstarz',{buyer,fulfillment:'pickup',items:[{kind:'product',id:product,variantId:variant,quantity:1}]},'foreign-key-1234'),/unavailable|not found/i);assert.equal((await db.query<{n:number;quantity:number;quantity_reserved:number}>('SELECT count(*)::int n FROM orders')).rows[0].n,0)}finally{await db.close()}});
test('variant stock reservations prevent overselling',async()=>{const {db,pool}=await fixture();try{const s=new CommerceOrders(pool,{receiptSecret:"fixture-receipt-secret-at-least-24-chars"});const c={buyer,fulfillment:'pickup',items:[{kind:'product',id:product,variantId:variant,quantity:2}]};await s.createOrder('gangstarz',c,'merch-key-1234');await assert.rejects(s.createOrder('gangstarz',c,'merch-key-5678'),/stock|sold out/i);assert.equal((await db.query<{n:number;quantity:number;quantity_reserved:number}>('SELECT quantity FROM product_variants')).rows[0].quantity,3)}finally{await db.close()}});
test('all-or-nothing cart rolls back ticket reservation on sold-out merch',async()=>{const {db,pool}=await fixture();try{await db.exec('UPDATE product_variants SET quantity=0');const s=new CommerceOrders(pool,{receiptSecret:"fixture-receipt-secret-at-least-24-chars"});await assert.rejects(s.createOrder('gangstarz',{buyer,fulfillment:'pickup',items:[{kind:'ticket',id:ticket,quantity:1},{kind:'product',id:product,variantId:variant,quantity:1}]},'atomic-cart-1234'));assert.equal((await db.query<{n:number;quantity:number;quantity_reserved:number}>('SELECT quantity_reserved FROM ticket_types')).rows[0].quantity_reserved,0);assert.equal((await db.query<{n:number;quantity:number;quantity_reserved:number}>('SELECT count(*)::int n FROM orders')).rows[0].n,0)}finally{await db.close()}});
test('private or draft events are absent from catalog and cannot be purchased',async()=>{const {db,pool}=await fixture();try{const s=new CommerceOrders(pool,{receiptSecret:"fixture-receipt-secret-at-least-24-chars"});for(const status of ['draft','published']){await db.query<{n:number;quantity:number;quantity_reserved:number}>('UPDATE events SET status=$1,is_private=true WHERE id=$2',[status,event]);assert.equal((await s.catalog('gangstarz')).events.length,0);await assert.rejects(s.createOrder('gangstarz',cart,'private-key-1234'),/unavailable/i)}}finally{await db.close()}});
test('hidden tiers and unpublished products cannot be purchased',async()=>{const {db,pool}=await fixture();try{const s=new CommerceOrders(pool,{receiptSecret:"fixture-receipt-secret-at-least-24-chars"});await db.exec('UPDATE ticket_types SET is_hidden=true; UPDATE products SET published_at=null');const c=await s.catalog('gangstarz');assert.equal(c.events[0]?.tickets.length??0,0);assert.equal(c.products.length,0);await assert.rejects(s.createOrder('gangstarz',cart,'hidden-key-1234'),/unavailable/i)}finally{await db.close()}});
test('unknown merchant setup disables new sales',async()=>{const {db,pool}=await fixture();try{await db.exec("UPDATE tenants SET settings='{}'");const s=new CommerceOrders(pool,{receiptSecret:"fixture-receipt-secret-at-least-24-chars"});assert.equal((await s.catalog('gangstarz')).salesEnabled,false);await assert.rejects(s.createOrder('gangstarz',cart,'disabled-key-1234'),/configured|enabled/i)}finally{await db.close()}});
test('physical orders require a configured fulfillment option',async()=>{const {db,pool}=await fixture();try{await db.exec("UPDATE tenants SET settings='{"+ '"commerce":{"enabled":true,"mode":"test"}' +"}'");const s=new CommerceOrders(pool,{receiptSecret:"fixture-receipt-secret-at-least-24-chars"});await assert.rejects(s.createOrder('gangstarz',{buyer,fulfillment:'shipping',items:[{kind:'product',id:product,variantId:variant,quantity:1}]},'shipping-key-1234'),/shipping|fulfillment/i)}finally{await db.close()}});

test('concurrent final-ticket purchases admit exactly one winner', {skip:!process.env.COMMERCE_TEST_DATABASE_URL},async()=>{const {db,pool}=await fixture();try{await db.exec('UPDATE ticket_types SET quantity_total=1');const orders=new CommerceOrders(pool,{receiptSecret:'fixture-receipt-secret-at-least-24-chars'});const results=await Promise.allSettled([orders.createOrder('gangstarz',{buyer,items:[{kind:'ticket',id:ticket,quantity:1}]},'concurrent-one-123'),orders.createOrder('gangstarz',{buyer,items:[{kind:'ticket',id:ticket,quantity:1}]},'concurrent-two-123')]);assert.equal(results.filter(result=>result.status==='fulfilled').length,1);assert.equal((await db.query<{n:number}>('SELECT count(*)::int n FROM orders')).rows[0].n,1);assert.equal((await db.query<{n:number}>('SELECT quantity_reserved n FROM ticket_types')).rows[0].n,1);}finally{await db.close()}});
test('catalog carries the presentation fields the public site renders from',async()=>{const {db,pool}=await fixture();try{
 await db.exec(`INSERT INTO venues(id,tenant_id,name,city) VALUES('55555555-5555-4555-8555-555555555555','11111111-1111-4111-8111-111111111111','RSVP Mainstage','Charlotte');
 UPDATE events SET venue_id='55555555-5555-4555-8555-555555555555',external_url='https://posh.vip/e/x',metadata='{"label":"GANGSTARZ PRESENTS"}';
 UPDATE products SET status='out_of_stock',metadata='{"externalUrl":"https://shop.example.com/p"}'`);
 const s=new CommerceOrders(pool,{receiptSecret:"fixture-receipt-secret-at-least-24-chars"});const c=await s.catalog('gangstarz');
 assert.equal(c.events[0].venue,'RSVP Mainstage');assert.equal(c.events[0].label,'GANGSTARZ PRESENTS');assert.equal(c.events[0].external_url,'https://posh.vip/e/x');
 assert.equal(c.products[0].status,'out_of_stock');assert.equal(c.products[0].external_url,'https://shop.example.com/p');
 await db.exec("UPDATE venues SET tenant_id='22222222-2222-4222-8222-222222222222'");assert.equal((await s.catalog('gangstarz')).events[0].venue,null,'foreign venue is never joined');
}finally{await db.close()}});
