import test from 'node:test';import assert from 'node:assert/strict';import{createHmac}from'node:crypto';
import{CommerceOrders}from'../../src/lib/commerce/orders';import{CommercePayments}from'../../src/lib/commerce/payments';import{verifyNotification,verifyCapability}from'../../src/lib/commerce/security';import type{Gateway,GatewayPayment}from'../../src/lib/commerce/gateway';import{fixture,buyer,ticket,tenant}from'./fixture';
const secret='fixture-receipt-secret-at-least-24-chars',webhook='fixture-webhook-secret-at-least-24-chars';
const paymentId='77777777-7777-4777-8777-777777777777';
async function setup(){const f=await fixture();const orders=new CommerceOrders(f.pool,{receiptSecret:secret});const checkout=await orders.createOrder('gangstarz',{buyer,items:[{kind:'ticket',id:ticket,quantity:2}]},'payment-fixture-123');let remote:GatewayPayment={id:paymentId,mode:'test',status:'pending',amount:5000,amount_refunded:0,currency:'usd',reference:checkout.id,metadata:{members_tenant_id:tenant},checkout_url:'https://checkout.stripe.com/test',expires_at:Math.floor(Date.now()/1000)+3600};let calls=0,fail=false;const gateway:Gateway={create:async()=>{calls++;if(fail)throw Error('timeout');return remote;},get:async()=>remote,refund:async()=>{remote={...remote,status:'refunded',amount_refunded:5000};return {payment:remote,refund:{id:'88888888-8888-4888-8888-888888888888',payment:paymentId,amount:5000,status:'succeeded' as const}};}};const service=new CommercePayments(f.pool,orders,gateway);return{...f,orders,checkout,service,remote:()=>remote,set:(patch:Partial<GatewayPayment>)=>{remote={...remote,...patch}},calls:()=>calls,fail:(value:boolean)=>{fail=value}};}
test('signature rejects tampering and stale replay; receipt capability is bound to exact tenant and checkout',()=>{const body='{"id":"event"}',now=1700000000,mac=createHmac('sha256',webhook).update(`${now}.${body}`).digest('hex');assert.equal(verifyNotification(webhook,`t=${now},v1=${mac}`,body,now),true);assert.equal(verifyNotification(webhook,`t=${now},v1=${mac}`,body+' ',now),false);assert.equal(verifyNotification(webhook,`t=${now},v1=${mac}`,body,now+301),false);assert.equal(verifyCapability('good','good'),true);assert.equal(verifyCapability('good','forged'),false);});
test('timeout retry uses same checkout and keeps reservation; duplicate checkout does not call gateway twice',async()=>{const f=await setup();try{f.fail(true);await assert.rejects(f.service.startCheckout(f.checkout.id,tenant));assert.equal((await f.db.query<{quantity_reserved:number}>('SELECT quantity_reserved FROM ticket_types')).rows[0].quantity_reserved,2);f.fail(false);const a=await f.service.startCheckout(f.checkout.id,tenant),b=await f.service.startCheckout(f.checkout.id,tenant);assert.equal(a.paymentId,paymentId);assert.equal(b.paymentId,paymentId);assert.equal(f.calls(),2);}finally{await f.db.close()}});
test('payment before attachment is verified remotely and fulfillment is exactly once',async()=>{const f=await setup();try{f.set({status:'succeeded',checkout_url:null});await f.service.applyPayment('evt_early',paymentId);await f.service.applyPayment('evt_early',paymentId);await f.service.applyPayment('evt_duplicate',paymentId);assert.equal((await f.db.query<{n:number}>('SELECT count(*)::int n FROM attendees')).rows[0].n,2);assert.equal((await f.db.query<{quantity_sold:number;quantity_reserved:number}>('SELECT quantity_sold,quantity_reserved FROM ticket_types')).rows[0].quantity_sold,2);assert.equal((await f.db.query<{quantity_reserved:number}>('SELECT quantity_reserved FROM ticket_types')).rows[0].quantity_reserved,0);}finally{await f.db.close()}});
test('wrong tenant, mode or amount cannot attach or fulfill',async()=>{for(const patch of [{amount:1},{mode:'live' as const},{metadata:{members_tenant_id:'foreign'}}]){const f=await setup();try{f.set({...patch,status:'succeeded'});await assert.rejects(f.service.applyPayment('evt_wrong',paymentId),/mismatch/i);assert.equal((await f.db.query<{n:number}>('SELECT count(*)::int n FROM attendees')).rows[0].n,0);}finally{await f.db.close()}}});
test('gateway terminal expiry releases once; pending gateway remains reserved regardless of local clock',async()=>{const f=await setup();try{f.set({expires_at:1});await f.service.applyPayment('evt_pending',paymentId);assert.equal((await f.db.query<{quantity_reserved:number}>('SELECT quantity_reserved FROM ticket_types')).rows[0].quantity_reserved,2);f.set({status:'expired',checkout_url:null});await f.service.applyPayment('evt_expired',paymentId);await f.service.applyPayment('evt_expired_twice',paymentId);assert.equal((await f.db.query<{quantity_reserved:number}>('SELECT quantity_reserved FROM ticket_types')).rows[0].quantity_reserved,0);}finally{await f.db.close()}});
test('full refund cancels tickets and stale paid notifications never restore validity',async()=>{const f=await setup();try{f.set({status:'succeeded',checkout_url:null});await f.service.applyPayment('evt_paid',paymentId);f.set({status:'refunded',amount_refunded:5000});await f.service.applyPayment('evt_refund',paymentId);f.set({status:'succeeded',amount_refunded:0});await f.service.applyPayment('evt_out_of_order',paymentId);assert.equal((await f.db.query<{n:number}>("SELECT count(*)::int n FROM attendees WHERE status='cancelled'")).rows[0].n,2);assert.equal((await f.db.query<{state:string}>('SELECT state FROM commerce_checkouts')).rows[0].state,'refunded');assert.equal((await f.db.query<{quantity_sold:number}>('SELECT quantity_sold FROM ticket_types')).rows[0].quantity_sold,2);}finally{await f.db.close()}});
test('refund retry returns same result while a changed refund payload conflicts',async()=>{const f=await setup();try{f.set({status:'succeeded',checkout_url:null});await f.service.applyPayment('evt_paid_for_refund',paymentId);const a=await f.service.refund(f.checkout.id,tenant,5000,'refund-request-123');const b=await f.service.refund(f.checkout.id,tenant,5000,'refund-request-123');assert.equal(a.state,'refunded');assert.equal(b.state,'refunded');await assert.rejects(f.service.refund(f.checkout.id,tenant,1000,'refund-request-123'),/retry|different/i);}finally{await f.db.close()}});

test('reconciliation recovers missing payment attachment without issuing a new charge',async()=>{const f=await setup();try{f.set({status:'succeeded',checkout_url:null});await f.service.applyPayment('evt_reconcile_fixture',paymentId);await f.service.reconcile(f.checkout.id,tenant);assert.equal(f.calls(),0);assert.equal((await f.db.query<{n:number}>('SELECT count(*)::int n FROM attendees')).rows[0].n,2);}finally{await f.db.close()}});
