import{z}from'zod';import{CommerceError,type CheckoutRow}from'./types';
const payment=z.object({id:z.uuid(),mode:z.enum(['test','live']),status:z.enum(['pending','succeeded','failed','expired','refunded','partially_refunded','disputed']),amount:z.number().int().min(50),amount_refunded:z.number().int().min(0),currency:z.literal('usd'),reference:z.string(),metadata:z.record(z.string(),z.unknown()),checkout_url:z.string().nullable(),expires_at:z.number().int().nullable()});
export type GatewayPayment=z.infer<typeof payment>;
export type Gateway={create:(input:CheckoutRow&{customer_email:string})=>Promise<GatewayPayment>;get:(id:string)=>Promise<GatewayPayment>;find?:(reference:string)=>Promise<GatewayPayment|null>;refund:(id:string,amount:number,key:string)=>Promise<{payment:GatewayPayment;refund:{id:string;payment:string;amount:number;status:'pending'|'succeeded'|'failed'|'canceled'}}>};
export class TollboothGateway implements Gateway{
 constructor(private options:{apiKey:string;mode:'test'|'live';origin?:string;fetch?:typeof fetch}){if(!options.apiKey.startsWith(`tb_${options.mode}_`))throw new CommerceError('Merchant payment credentials are not configured for this mode',503);const origin=new URL(options.origin??'https://tollbooth.axxes.club');if(origin.origin!=='https://tollbooth.axxes.club'||origin.pathname!=='/')throw new CommerceError('Payment gateway origin is not trusted',503);}
 private async request(path:string,body?:unknown,key?:string){let response:Response;try{response=await(this.options.fetch??fetch)(new URL(path,this.options.origin??'https://tollbooth.axxes.club'),{method:body?'POST':'GET',headers:{authorization:`Bearer ${this.options.apiKey}`,...(body?{'content-type':'application/json'}:{}),...(key?{'idempotency-key':key}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(25000),redirect:'error',cache:'no-store'});}catch{throw new CommerceError('Payment gateway is unavailable; retry this checkout',503);}if(!response.ok)throw new CommerceError(response.status===409?'Merchant setup or payment request is not ready':'Payment gateway request failed',response.status===409?503:502);const value=await response.json();return value.data??value;}
 async verifyMerchant(tenantId:string){const account=z.object({tenant_id:z.string(),mode:z.enum(['test','live']),ready:z.boolean()}).parse(await this.request('/api/v1/account'));if(account.tenant_id!==tenantId||account.mode!==this.options.mode)throw new CommerceError('Payment merchant identity or mode mismatch',409);if(!account.ready)throw new CommerceError('Payment merchant and platform setup are not ready',503);return account;}
 async create(input:CheckoutRow&{customer_email:string}){return payment.parse(await this.request('/api/v1/checkout-sessions',{amount:input.amount,currency:input.currency,description:'Gangstarz order '+input.id,customer_email:input.customer_email,reference:input.id,metadata:{members_tenant_id:input.tenant_id},success_url:'https://gangstarz.axxes.club/shop',cancel_url:'https://gangstarz.axxes.club/shop'},`members:${input.mode}:${input.id}`));}
 async get(id:string){return payment.parse(await this.request('/api/v1/payments/'+z.uuid().parse(id)));}
 async find(reference:string){const query=new URLSearchParams({reference:z.uuid().parse(reference),mode:this.options.mode,limit:'2'});const matches=z.array(payment).parse(await this.request('/api/v1/payments?'+query));if(matches.length>1)throw new CommerceError('Payment reference requires operator reconciliation',409);return matches[0]??null;}
 async refund(id:string,amount:number,key:string){const refund=z.object({id:z.uuid(),payment:z.uuid(),amount:z.number().int().positive(),status:z.enum(['pending','succeeded','failed','canceled'])}).parse(await this.request('/api/v1/refunds',{payment_id:id,amount,reason:'requested_by_customer'},key));return {payment:await this.get(id),refund};}
}
