import{CommerceError}from'./types';import{z}from'zod';
type Handlers={catalog:()=>Promise<unknown>;checkout:(body:unknown,key:string)=>Promise<unknown>;receipt:(id:string,capability:string)=>Promise<unknown>;operator:(request:Request,body?:unknown)=>Promise<unknown>;webhook:(request:Request,body:string)=>Promise<unknown>};
const headers={'cache-control':'no-store'};
async function text(request:Request,limit:number){const reader=request.body?.getReader();if(!reader)return '';const decoder=new TextDecoder();let length=0,value='';while(true){const chunk=await reader.read();if(chunk.done)break;length+=chunk.value.length;if(length>limit){await reader.cancel();throw new CommerceError('Request is too large',413);}value+=decoder.decode(chunk.value,{stream:true});}return value+decoder.decode();}
export function commerceHttp(handlers:Handlers){const wrap=(run:()=>Promise<unknown>)=>run().then(data=>Response.json(data,{headers})).catch(error=>Response.json({error:error instanceof CommerceError?error.message:error instanceof z.ZodError?'Invalid commerce request':'Commerce is unavailable'},{status:error instanceof CommerceError?error.status:error instanceof z.ZodError?400:503,headers}));const origin=(request:Request,operator=false)=>{if(!(operator?['https://members.axxes.club']:['https://members.axxes.club','https://gangstarz.axxes.club']).includes(request.headers.get('origin')??''))throw new CommerceError('Request origin denied',403);};return{
 catalog:()=>wrap(handlers.catalog),
 checkout:(request:Request)=>wrap(async()=>{origin(request);let body:unknown;try{body=JSON.parse(await text(request,16384));}catch(error){if(error instanceof CommerceError)throw error;throw new CommerceError('Invalid checkout request');}const key=request.headers.get('idempotency-key')??'';if(!/^[a-zA-Z0-9_-]{12,100}$/.test(key))throw new CommerceError('Checkout idempotency key required');return handlers.checkout(body,key);}),
 receipt:(request:Request,id:string)=>wrap(async()=>{z.uuid().parse(id);const capability=/^Bearer (.{1,200})$/.exec(request.headers.get('authorization')??'')?.[1];if(!capability)throw new CommerceError('Buyer receipt capability required',403);return handlers.receipt(id,capability);}),
 operator:(request:Request)=>wrap(async()=>{if(request.method==='GET')return handlers.operator(request);origin(request,true);let body:unknown;try{body=JSON.parse(await text(request,16384));}catch(error){if(error instanceof CommerceError)throw error;throw new CommerceError('Invalid commerce request');}return handlers.operator(request,body);}),
 webhook:(request:Request)=>wrap(async()=>handlers.webhook(request,await text(request,1_000_000)))
};}
