import{createCipheriv,createDecipheriv,createHash,randomBytes}from'node:crypto';import{z}from'zod';import{CommerceError,type Policy,type SqlPool}from'./types';import{TollboothGateway}from'./gateway';import{CommerceAdministration}from'./administration';
const credentials=z.object({apiKey:z.string().min(24),webhookSecret:z.string().min(24)}).strict();
function encryptionKey(secret:string){if(secret.length<32)throw new CommerceError('Server commerce encryption key is not configured',503);return createHash('sha256').update('members-commerce-credentials:'+secret).digest();}
export function sealCredentials(secret:string,value:z.infer<typeof credentials>){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',encryptionKey(secret),iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(credentials.parse(value)),'utf8'),cipher.final()]);return [iv,cipher.getAuthTag(),encrypted].map(x=>x.toString('base64url')).join('.');}
export function openCredentials(secret:string,value:string){const parts=value.split('.');if(parts.length!==3)throw new CommerceError('Stored merchant configuration is invalid',503);const [iv,tag,body]=parts.map(x=>Buffer.from(x,'base64url'));const cipher=createDecipheriv('aes-256-gcm',encryptionKey(secret),iv);cipher.setAuthTag(tag);return credentials.parse(JSON.parse(Buffer.concat([cipher.update(body),cipher.final()]).toString('utf8')));}
export const policySchema=z.object({enabled:z.boolean(),mode:z.enum(['test','live']),taxBps:z.number().int().min(0).max(10000).default(0),pickup:z.object({instructions:z.string().trim().min(1).max(1000)}).optional(),shipping:z.object({flatCents:z.number().int().min(0).max(1_000_000),countries:z.array(z.string().regex(/^[A-Z]{2}$/)).min(1).max(100)}).optional()}).strict();
export class CommerceMerchant{
 constructor(private pool:SqlPool,private admin:CommerceAdministration,private secret:string){}
 async configured(tenantId:string,mode:'test'|'live'){const c=await this.pool.connect();try{return (await c.query('SELECT 1 FROM commerce_merchants WHERE tenant_id=$1 AND mode=$2',[tenantId,mode])).rows.length>0;}finally{c.release();}}
 async get(tenantId:string,mode:'test'|'live',verify=true){const c=await this.pool.connect();let row:{credentials_ciphertext:string}|undefined;try{row=(await c.query<{credentials_ciphertext:string}>('SELECT credentials_ciphertext FROM commerce_merchants WHERE tenant_id=$1 AND mode=$2',[tenantId,mode])).rows[0];}finally{c.release();}if(!row)throw new CommerceError('This workspace has not configured its payment merchant',503);const value=openCredentials(this.secret,row.credentials_ciphertext),gateway=new TollboothGateway({apiKey:value.apiKey,mode});if(verify)await gateway.verifyMerchant(tenantId);return{gateway,webhookSecret:value.webhookSecret};}
 async configure(tenantId:string,userId:string,mode:'test'|'live',raw:unknown){await this.admin.withOperator(tenantId,userId,true,async()=>{});const value=credentials.parse(raw),gateway=new TollboothGateway({apiKey:value.apiKey,mode});await gateway.verifyMerchant(tenantId);const encrypted=sealCredentials(this.secret,value);return this.admin.withOperator(tenantId,userId,true,async c=>{await c.query('INSERT INTO commerce_merchants(tenant_id,mode,credentials_ciphertext,updated_by) VALUES($1,$2,$3,$4) ON CONFLICT(tenant_id,mode) DO UPDATE SET credentials_ciphertext=EXCLUDED.credentials_ciphertext,updated_by=EXCLUDED.updated_by,verified_at=now()',[tenantId,mode,encrypted,userId]);return{configured:true,mode};});}
 async savePolicy(tenantId:string,userId:string,raw:unknown){await this.admin.withOperator(tenantId,userId,true,async()=>{});const policy=policySchema.parse(raw);if(policy.enabled)await this.get(tenantId,policy.mode);return this.admin.withOperator(tenantId,userId,true,async c=>{await c.query("UPDATE tenants SET settings=jsonb_set(coalesce(settings,'{}'::jsonb),'{commerce}',$2::jsonb) WHERE id=$1",[tenantId,JSON.stringify(policy)]);return{policy:policy as Policy};});}
}
