import{randomUUID}from'node:crypto';import{CommerceError,transaction,type SqlClient,type SqlPool,type CheckoutRow}from'./types';import{CommerceOrders}from'./orders';import type{Gateway,GatewayPayment}from'./gateway';
type Reservation={id:string;kind:'ticket'|'product';resource_id:string;product_id:string|null;event_id:string|null;quantity:number;state:'reserved'|'consumed'|'released'};
export class CommercePayments{
 constructor(private pool:SqlPool,private orders:CommerceOrders,private gateway:Gateway){}
 private verify(row:CheckoutRow,p:GatewayPayment){if(p.reference!==row.id||p.mode!==row.mode||p.amount!==row.amount||p.currency!==row.currency||p.amount_refunded>p.amount||p.metadata.members_tenant_id!==row.tenant_id||(p.status==='refunded'&&p.amount_refunded!==p.amount)||(p.status==='partially_refunded'&&(p.amount_refunded<=0||p.amount_refunded>=p.amount))||(row.payment_id&&row.payment_id!==p.id))throw new CommerceError('Payment identity, tenant, mode or amount mismatch',409);}
 async startCheckout(id:string,tenantId:string){
  const leased=await transaction(this.pool,async c=>{const row=(await c.query<CheckoutRow&{gateway_lease_until:Date|null;customer_email:string}>('SELECT x.*,o.customer_email FROM commerce_checkouts x JOIN orders o ON o.id=x.id AND o.tenant_id=x.tenant_id WHERE x.id=$1 AND x.tenant_id=$2 FOR UPDATE OF x',[id,tenantId])).rows[0];if(!row)throw new CommerceError('Checkout not found',404);if(row.payment_id||row.state!=='awaiting_gateway')return {row,lease:null};if(row.gateway_lease_until&&new Date(row.gateway_lease_until).getTime()>Date.now())throw new CommerceError('Checkout is starting; retry the same request',409);const lease=new Date(Date.now()+60000);await c.query('UPDATE commerce_checkouts SET gateway_lease_until=$2 WHERE id=$1',[id,lease]);return {row,lease};});
  if(!leased.lease)return this.orders.checkout(leased.row);
  try{const remote=await this.gateway.create(leased.row);this.verify(leased.row,remote);await this.applyVerified(`attach:${remote.id}:${remote.status}:${remote.amount_refunded}`,remote);const c=await this.pool.connect();try{return this.orders.checkout((await c.query<CheckoutRow>('SELECT * FROM commerce_checkouts WHERE id=$1 AND tenant_id=$2',[id,tenantId])).rows[0]);}finally{c.release();}}
  finally{const c=await this.pool.connect();try{await c.query('UPDATE commerce_checkouts SET gateway_lease_until=NULL WHERE id=$1 AND gateway_lease_until=$2',[id,leased.lease]);}finally{c.release();}}
 }
 async applyPayment(notificationId:string,paymentId:string){const payment=await this.gateway.get(paymentId);return this.applyVerified(notificationId,payment);}
 async reconcile(id:string,tenantId:string){const client=await this.pool.connect();let row:CheckoutRow|undefined;try{row=(await client.query<CheckoutRow>('SELECT * FROM commerce_checkouts WHERE id=$1 AND tenant_id=$2',[id,tenantId])).rows[0];}finally{client.release();}if(!row)throw new CommerceError('Checkout not found',404);const payment=row.payment_id?await this.gateway.get(row.payment_id):await this.gateway.find?.(row.id);if(!payment)return{reconciled:false};this.verify(row,payment);await this.applyVerified(`reconcile:${payment.id}:${payment.status}:${payment.amount_refunded}`,payment);return{reconciled:true};}
 private async release(c:SqlClient,row:CheckoutRow){const reservations=(await c.query<Reservation>("SELECT * FROM commerce_reservations WHERE checkout_id=$1 AND tenant_id=$2 AND state='reserved' ORDER BY resource_id FOR UPDATE",[row.id,row.tenant_id])).rows;for(const r of reservations){if(r.kind==='ticket')await c.query('UPDATE ticket_types SET quantity_reserved=greatest(0,coalesce(quantity_reserved,0)-$3) WHERE id=$1 AND tenant_id=$2',[r.resource_id,row.tenant_id,r.quantity]);await c.query("UPDATE commerce_reservations SET state='released' WHERE id=$1 AND state='reserved'",[r.id]);}}
 private async fulfill(c:SqlClient,row:CheckoutRow){if(['failed','expired','refunded'].includes(row.state))throw new CommerceError('Terminal reservation cannot be reopened',409);const order=(await c.query<{customer_email:string;customer_first_name:string;customer_last_name:string}>('SELECT customer_email,customer_first_name,customer_last_name FROM orders WHERE id=$1 AND tenant_id=$2',[row.id,row.tenant_id])).rows[0];const reservations=(await c.query<Reservation>("SELECT * FROM commerce_reservations WHERE checkout_id=$1 AND tenant_id=$2 AND state='reserved' ORDER BY resource_id FOR UPDATE",[row.id,row.tenant_id])).rows;
  for(const r of reservations){if(r.kind==='ticket'){await c.query('UPDATE ticket_types SET quantity_reserved=greatest(0,coalesce(quantity_reserved,0)-$3),quantity_sold=coalesce(quantity_sold,0)+$3 WHERE id=$1 AND tenant_id=$2',[r.resource_id,row.tenant_id,r.quantity]);for(let i=0;i<r.quantity;i++)await c.query("INSERT INTO attendees(id,tenant_id,event_id,ticket_type_id,order_id,first_name,last_name,email,ticket_code,status,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'confirmed',$10)",[randomUUID(),row.tenant_id,r.event_id,r.resource_id,row.id,order.customer_first_name,order.customer_last_name,order.customer_email,'GS-'+randomUUID().replaceAll('-',''),JSON.stringify({commerceCheckoutId:row.id,commerceMode:row.mode})]);}
   else{const variant=(await c.query<{id:string}>('SELECT id FROM product_variants WHERE id=$1 AND product_id=$2 AND tenant_id=$3',[r.resource_id,r.product_id,row.tenant_id])).rows.length>0;const table=variant?'product_variants':'products';const changed=await c.query<{id:string}>(`UPDATE ${table} SET quantity=quantity-$3 WHERE id=$1 AND tenant_id=$2 AND quantity>=$3 RETURNING id`,[r.resource_id,row.tenant_id,r.quantity]);if(!changed.rows.length)throw new CommerceError('Reserved inventory requires operator reconciliation',409);}
   await c.query("UPDATE commerce_reservations SET state='consumed' WHERE id=$1 AND state='reserved'",[r.id]);}
  await c.query("UPDATE orders SET status='confirmed',payment_status='captured',paid_at=coalesce(paid_at,now()),external_order_id=$3,external_platform='tollbooth',updated_at=now() WHERE id=$1 AND tenant_id=$2",[row.id,row.tenant_id,row.payment_id]);
 }
 private async applyVerified(notificationId:string,p:GatewayPayment){if(!notificationId||notificationId.length>200)throw new CommerceError('Invalid notification identifier');return transaction(this.pool,async c=>{
  const row=(await c.query<CheckoutRow&{amount_refunded:number}>('SELECT * FROM commerce_checkouts WHERE id=$1 FOR UPDATE',[p.reference])).rows[0];if(!row)throw new CommerceError('Checkout not found',404);this.verify(row,p);
  const existing=(await c.query<{checkout_id:string;payment_id:string}>('SELECT checkout_id,payment_id FROM commerce_notifications WHERE notification_id=$1',[notificationId])).rows[0];if(existing){if(existing.checkout_id!==row.id||existing.payment_id!==p.id)throw new CommerceError('Notification identity mismatch',409);return this.orders.checkout(row);}
  await c.query('UPDATE commerce_checkouts SET payment_id=$2,checkout_url=$3,updated_at=now() WHERE id=$1',[row.id,p.id,p.status==='pending'?p.checkout_url:null]);row.payment_id=p.id;
  let state=row.state;const refunded=Math.max(row.amount_refunded,p.amount_refunded);
  if(p.status==='pending'){if(state==='awaiting_gateway')state='pending';}
  else if(['failed','expired'].includes(p.status)){if(['awaiting_gateway','pending'].includes(state)){await this.release(c,row);state=p.status;await c.query("UPDATE orders SET status='cancelled',payment_status='failed',cancelled_at=now(),updated_at=now() WHERE id=$1 AND tenant_id=$2",[row.id,row.tenant_id]);}}
  else if(p.status==='disputed'){await c.query("UPDATE attendees SET status='cancelled' WHERE order_id=$1 AND tenant_id=$2",[row.id,row.tenant_id]);await c.query("UPDATE orders SET status='cancelled',payment_status='failed',updated_at=now() WHERE id=$1 AND tenant_id=$2",[row.id,row.tenant_id]);}
  else if(refunded===row.amount){if(['awaiting_gateway','pending'].includes(state))await this.release(c,row);await c.query("UPDATE attendees SET status='cancelled' WHERE order_id=$1 AND tenant_id=$2",[row.id,row.tenant_id]);state='refunded';await c.query("UPDATE orders SET status='refunded',payment_status='refunded',refunded_at=coalesce(refunded_at,now()),updated_at=now() WHERE id=$1 AND tenant_id=$2",[row.id,row.tenant_id]);}
  else{if(!['paid','partially_refunded','refunded'].includes(state))await this.fulfill(c,row);state=refunded>0?'partially_refunded':state==='refunded'?'refunded':'paid';if(refunded>0)await c.query("UPDATE orders SET payment_status='partially_refunded',updated_at=now() WHERE id=$1 AND tenant_id=$2",[row.id,row.tenant_id]);}
  await c.query('UPDATE commerce_checkouts SET state=$2,amount_refunded=$3,updated_at=now() WHERE id=$1',[row.id,state,refunded]);await c.query('INSERT INTO commerce_notifications(notification_id,checkout_id,payment_id) VALUES($1,$2,$3)',[notificationId,row.id,p.id]);return this.orders.checkout({...row,state});
 });}
 async refund(id:string,tenantId:string,amount:number,key:string){
  if(!Number.isInteger(amount)||amount<1||!/^[a-zA-Z0-9_-]{12,100}$/.test(key))throw new CommerceError('Invalid refund request');
  const request=await transaction(this.pool,async c=>{
   const row=(await c.query<CheckoutRow&{amount_refunded:number}>('SELECT * FROM commerce_checkouts WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[id,tenantId])).rows[0];
   if(!row||!row.payment_id)throw new CommerceError('Paid checkout not found',404);
   const existing=(await c.query<{amount:number;state:string;created_at:Date}>('SELECT amount,state,created_at FROM commerce_refund_requests WHERE checkout_id=$1 AND tenant_id=$2 AND idempotency_key=$3',[id,tenantId,key])).rows[0];
   if(existing){if(existing.amount!==amount)throw new CommerceError('Refund retry payload is different',409);if(existing.state==='confirmed')return{row,complete:true};if(Date.now()-new Date(existing.created_at).getTime()>23*3600000)throw new CommerceError('Pending refund requires gateway reconciliation before retry',409);}
   else{const pending=(await c.query("SELECT 1 FROM commerce_refund_requests WHERE checkout_id=$1 AND tenant_id=$2 AND state='pending' LIMIT 1",[id,tenantId])).rows.length;if(pending)throw new CommerceError('Pending refund requires gateway reconciliation before another refund',409);if(!['paid','partially_refunded'].includes(row.state))throw new CommerceError('Paid checkout not found',404);if(amount>row.amount-row.amount_refunded)throw new CommerceError('Refund exceeds remaining paid amount');await c.query('INSERT INTO commerce_refund_requests(tenant_id,checkout_id,idempotency_key,amount) VALUES($1,$2,$3,$4)',[tenantId,id,key,amount]);}
   return{row,complete:false};
  });
  if(request.complete)return this.orders.checkout(request.row);
  const result=await this.gateway.refund(request.row.payment_id!,amount,`members-refund:${request.row.mode}:${id}:${key}`);
  if(result.refund.payment!==request.row.payment_id||result.refund.amount!==amount)throw new CommerceError('Refund identity or amount mismatch',409);
  this.verify(request.row,result.payment);
  const checkout=await this.applyVerified(`refund:${result.refund.id}:${result.payment.amount_refunded}`,result.payment);
  if(result.refund.status!=='succeeded')throw new CommerceError('Refund is pending confirmation or requires operator review',409);
  const c=await this.pool.connect();try{await c.query("UPDATE commerce_refund_requests SET state='confirmed',provider_refund_id=$4 WHERE checkout_id=$1 AND tenant_id=$2 AND idempotency_key=$3",[id,tenantId,key,result.refund.id]);}finally{c.release();}
  return checkout;
 }
}
