import{z}from'zod';import{auth}from'../auth';import{CommerceError}from'./types';import{commerceHttp}from'./http';import{verifyNotification}from'./security';import{commerceAdmin,commerceOrders,commerceMerchant,commercePayments,gangstarzCommerce}from'./runtime';
const inventory=z.object({action:z.literal('inventory'),kind:z.enum(['ticket','product','variant']),id:z.uuid(),price:z.string().regex(/^\d+(\.\d{1,2})?$/),quantity:z.number().int().min(0).max(1000000)}).strict();
const action=z.discriminatedUnion('action',[inventory,z.object({action:z.literal('merchant'),mode:z.enum(['test','live']),apiKey:z.string(),webhookSecret:z.string()}).strict(),z.object({action:z.literal('policy'),policy:z.unknown()}).strict(),z.object({action:z.literal('refund'),id:z.uuid(),amount:z.number().int().positive(),key:z.string()}).strict(),z.object({action:z.literal('fulfill'),id:z.uuid()}).strict(),z.object({action:z.literal('return'),itemId:z.uuid(),quantity:z.number().int().positive(),key:z.string()}).strict(),z.object({action:z.literal('scan'),ticketCode:z.string(),mode:z.enum(['test','live'])}).strict()]);
export const commerceRoutes=commerceHttp({
 catalog:async()=>{const context=await gangstarzCommerce();const catalog=await commerceOrders.catalog('gangstarz');return{...catalog,salesEnabled:catalog.salesEnabled&&await commerceMerchant.configured(context.tenantId,catalog.mode==='live'?'live':'test')};},
 checkout:async(body,key)=>{const context=await gangstarzCommerce();if(context.policy.enabled!==true)throw new CommerceError('Native sales are not enabled; existing external tickets remain available',503);const mode=context.policy.mode==='live'?'live':'test';const {payments}=await commercePayments(mode);const checkout=await commerceOrders.createOrder('gangstarz',body,key);return payments.startCheckout(checkout.id,context.tenantId);},
 receipt:(id,capability)=>commerceAdmin.receipt(id,capability),
 operator:async(request,body)=>{const session=await auth.api.getSession({headers:request.headers});if(!session?.user)throw new CommerceError('Sign in to manage commerce',401);const {tenantId,policy}=await gangstarzCommerce();const userId=session.user.id;if(request.method==='GET'){const setup=await commerceAdmin.withOperator(tenantId,userId,false,async c=>({merchants:(await c.query('SELECT mode,verified_at FROM commerce_merchants WHERE tenant_id=$1',[tenantId])).rows,events:(await c.query("SELECT id,name,status,starts_at FROM events WHERE tenant_id=$1 AND deleted_at IS NULL ORDER BY starts_at DESC LIMIT 100",[tenantId])).rows,tickets:(await c.query('SELECT id,event_id,name,price,quantity_total,quantity_sold,quantity_reserved FROM ticket_types WHERE tenant_id=$1 AND deleted_at IS NULL ORDER BY name',[tenantId])).rows,products:(await c.query('SELECT id,name,price,quantity,has_variants FROM products WHERE tenant_id=$1 AND deleted_at IS NULL ORDER BY name',[tenantId])).rows,variants:(await c.query('SELECT id,product_id,name,price,quantity FROM product_variants WHERE tenant_id=$1 AND deleted_at IS NULL ORDER BY name',[tenantId])).rows}));return{...setup,policy,orders:await commerceAdmin.ordersFor(tenantId,userId)};}
 const value=action.parse(body);
 if(value.action==='merchant')return commerceMerchant.configure(tenantId,userId,value.mode,{apiKey:value.apiKey,webhookSecret:value.webhookSecret});
 if(value.action==='policy')return commerceMerchant.savePolicy(tenantId,userId,value.policy);
 if(value.action==='inventory')return commerceAdmin.setInventory(tenantId,userId,value);
 if(value.action==='scan')return commerceAdmin.scan(tenantId,userId,value.ticketCode,value.mode);
 if(value.action==='fulfill')return commerceAdmin.fulfill(tenantId,userId,value.id);
 if(value.action==='return')return commerceAdmin.recordReturn(tenantId,userId,value.itemId,value.quantity,value.key);
 await commerceAdmin.withOperator(tenantId,userId,true,async()=>{});const mode=(await commerceAdmin.withOperator(tenantId,userId,true,async c=>(await c.query<{mode:'test'|'live'}>('SELECT mode FROM commerce_checkouts WHERE id=$1 AND tenant_id=$2',[value.id,tenantId])).rows[0]?.mode));if(!mode)throw new CommerceError('Order not found',404);const {payments}=await commercePayments(mode);await commerceAdmin.withOperator(tenantId,userId,true,async()=>{});return payments.refund(value.id,tenantId,value.amount,value.key);
 },
 webhook:async(request,body)=>{let event:unknown;try{event=JSON.parse(body);}catch{throw new CommerceError('Invalid payment notification');}const notification=z.object({id:z.string().min(1).max(200),mode:z.enum(['test','live']),type:z.enum(['payment.created','payment.succeeded','payment.failed','payment.expired','payment.refunded','payment.partially_refunded','payment.disputed','refund.created']),data:z.object({object:z.object({id:z.uuid(),payment:z.uuid().optional()})})}).parse(event);const {payments,webhookSecret}=await commercePayments(notification.mode,false);if(!verifyNotification(webhookSecret,request.headers.get('tollbooth-signature')??'',body))throw new CommerceError('Payment signature denied',401);const paymentId=notification.type==='refund.created'?notification.data.object.payment:notification.data.object.id;if(!paymentId)throw new CommerceError('Payment identity required');return payments.applyPayment(notification.id,paymentId);}
});
