import { PlatformError, type SubjectRef, type DirectoryQuery, type Page, type UserSummary, type OrganizationSummary, type UserDetails, type OrganizationDetails } from './contracts';
import { parseDirectoryQuery, parseUser, parseOrganization, parseMembership, parseInvitation } from './validation';
export interface Sql { query(text:string,values?:unknown[]):Promise<{rows:Record<string,unknown>[]}>; }
export const AUTHORITY='axxes-shared';
const iso=(v:unknown)=>v instanceof Date?v.toISOString():String(v);
const ref=(id:unknown)=>({authorityId:AUTHORITY,id:String(id)});
export function assertAuthority(s:SubjectRef){if(s.authorityId!==AUTHORITY)throw new PlatformError(404,'SUBJECT_NOT_FOUND','This identity authority is not connected.');}
export function createDirectory(db:Sql,policyReady=false,services:string[]=[]){
 const userVersion=`md5(u.updated_at::text || coalesce((SELECT string_agg(m.id::text || m.role || m.updated_at::text || coalesce(m.deleted_at::text,''),',' ORDER BY m.id) FROM tenant_memberships m WHERE m.user_id=u.id),'') ${policyReady?"|| coalesce(p.revision::text,'0')":''})`;
 const orgVersion=`md5(t.updated_at::text || t.status || coalesce((SELECT string_agg(m.id::text || m.role || m.updated_at::text || coalesce(m.deleted_at::text,''),',' ORDER BY m.id) FROM tenant_memberships m WHERE m.tenant_id=t.id),'') ${policyReady?"|| coalesce(p.revision::text,'0')":''})`;
 const userSelect=`SELECT u.id,u.name,u.email,u.email_verified,u.is_superadmin,u.created_at,${userVersion} AS version,${policyReady?"coalesce(p.state,'active')":"'active'"} AS state,(SELECT count(*)::int FROM tenant_memberships m JOIN tenants t ON t.id=m.tenant_id WHERE m.user_id=u.id AND m.deleted_at IS NULL AND t.deleted_at IS NULL) AS count FROM "user" u ${policyReady?"LEFT JOIN platform_subject_policy p ON p.subject_kind='user' AND p.subject_id=u.id":''}`;
 const orgSelect=`SELECT t.id,t.name,t.slug,t.status,t.created_at,${orgVersion} AS version,o.id AS owner_id,o.name AS owner_name,o.email AS owner_email,(SELECT count(*)::int FROM tenant_memberships m WHERE m.tenant_id=t.id AND m.deleted_at IS NULL) AS count FROM tenants t LEFT JOIN "user" o ON o.id=t.owner_id ${policyReady?"LEFT JOIN platform_subject_policy p ON p.subject_kind='organization' AND p.subject_id=t.id::text":''}`;
 const user=(r:Record<string,unknown>)=>parseUser({subject:ref(r.id),name:r.name,email:r.email,emailVerified:r.email_verified,state:r.state,version:r.version,createdAt:iso(r.created_at),organizationCount:r.count,protected:r.is_superadmin});
 const organization=(r:Record<string,unknown>)=>parseOrganization({subject:ref(r.id),name:r.name,slug:r.slug,state:r.status,version:r.version,createdAt:iso(r.created_at),memberCount:r.count,owner:r.owner_id?{id:r.owner_id,name:r.owner_name,email:r.owner_email}:null});
 async function list<T>(query:DirectoryQuery,kind:'user'|'organization',parse:(r:Record<string,unknown>)=>T):Promise<Page<T>>{
  const q=parseDirectoryQuery(query),values:unknown[]=[],conditions:string[]=[];const alias=kind==='user'?'u':'t';
  const param=(v:unknown)=>{values.push(v);return '$'+values.length;};
  if(kind==='organization')conditions.push('t.deleted_at IS NULL');
  if(q.query){const n=param('%'+q.query.replace(/[\%_]/g,'\\$&')+'%');conditions.push(`(${alias}.name ILIKE ${n} OR ${kind==='user'?'u.email':'t.slug'} ILIKE ${n} OR ${alias}.id::text ILIKE ${n})`);}
  if(q.cursor){const c=JSON.parse(Buffer.from(q.cursor,'base64url').toString());conditions.push(`(${alias}.created_at,${alias}.id::text)>(${param(c.createdAt)}::timestamptz,${param(c.id)})`);}
  if(q.state)conditions.push(`${kind==='user'?(policyReady?"coalesce(p.state,'active')":"'active'"):'t.status'}=${param(q.state)}`);
  if(q.organization){assertAuthority(q.organization);conditions.push(`EXISTS(SELECT 1 FROM tenant_memberships f WHERE f.user_id=u.id AND f.tenant_id=${param(q.organization.id)}::uuid AND f.deleted_at IS NULL)`);}
  if(q.serviceId)throw new PlatformError(400,'UNSUPPORTED_FILTER','Service access filtering is not supported until enforcement is verified.');
  const rows=(await db.query((kind==='user'?userSelect:orgSelect)+(conditions.length?' WHERE '+conditions.join(' AND '):'')+` ORDER BY ${alias}.created_at,${alias}.id::text LIMIT ${param(q.limit+1)}`,values)).rows;
  const shown=rows.slice(0,q.limit),last=shown.at(-1);return {items:shown.map(parse),nextCursor:rows.length>q.limit&&last?Buffer.from(JSON.stringify({createdAt:iso(last.created_at),id:last.id})).toString('base64url'):null,observedAt:new Date().toISOString()};
 }
 async function memberships(kind:'user'|'organization',id:string){const rows=(await db.query(`SELECT m.id,m.tenant_id,m.user_id,m.role,m.joined_at,t.name AS organization_name,u.name,u.email FROM tenant_memberships m JOIN tenants t ON t.id=m.tenant_id JOIN "user" u ON u.id=m.user_id WHERE m.${kind==='user'?'user_id':'tenant_id'}=$1 AND m.deleted_at IS NULL AND t.deleted_at IS NULL ORDER BY t.name,u.name,m.id LIMIT 1000`,[id])).rows;return rows.map(r=>parseMembership({id:r.id,organization:ref(r.tenant_id),user:ref(r.user_id),organizationName:r.organization_name,name:r.name,email:r.email,role:r.role,joinedAt:iso(r.joined_at)}));}
 async function invitations(kind:'user'|'organization',id:string){const rows=(await db.query(`SELECT i.id,i.tenant_id,i.email,i.role,i.status,i.expires_at ${policyReady?",d.state AS delivery_state":""} FROM tenant_invitations i ${policyReady?"LEFT JOIN platform_invitation_delivery d ON d.invitation_id=i.id":""} WHERE ${kind==='user'?'lower(i.email)=(SELECT lower(email) FROM "user" WHERE id=$1)':'i.tenant_id=$1'} ORDER BY i.created_at DESC,i.id LIMIT 1000`,[id])).rows;return rows.map(r=>parseInvitation({id:r.id,organization:ref(r.tenant_id),email:r.email,role:r.role,state:r.status,expiresAt:iso(r.expires_at),...(r.delivery_state?{deliveryState:r.delivery_state}:{})}));}
 async function access(kind:'user'|'organization',id:string){if(!policyReady||!services.length)return [];const rows=(await db.query(`SELECT user_id,tenant_id,service_id,allowed FROM platform_entitlements WHERE ${kind==='user'?'user_id':'tenant_id'}=$1 ORDER BY service_id LIMIT 1000`,[id])).rows;return rows.map(r=>({serviceId:String(r.service_id),organization:ref(r.tenant_id),state:r.allowed?'allowed' as const:'denied' as const,enforcement:services.includes(String(r.service_id))?'verified' as const:'unverified' as const,observedAt:new Date().toISOString()}));}
 return {
  listUsers:(q:DirectoryQuery)=>list<UserSummary>(q,'user',user),listOrganizations:(q:DirectoryQuery)=>list<OrganizationSummary>(q,'organization',organization),
  async getUser(s:SubjectRef):Promise<UserDetails>{assertAuthority(s);const r=(await db.query(userSelect+' WHERE u.id=$1',[s.id])).rows[0];if(!r)throw new PlatformError(404,'SUBJECT_NOT_FOUND','User not found.');return {...user(r),memberships:await memberships('user',s.id),invitations:await invitations('user',s.id),access:await access('user',s.id)};},
  async getOrganization(s:SubjectRef):Promise<OrganizationDetails>{assertAuthority(s);const r=(await db.query(orgSelect+' WHERE t.id=$1 AND t.deleted_at IS NULL',[s.id])).rows[0];if(!r)throw new PlatformError(404,'SUBJECT_NOT_FOUND','Organization not found.');return {...organization(r),memberships:await memberships('organization',s.id),invitations:await invitations('organization',s.id),access:await access('organization',s.id)};},
 };
}
