import{test}from'node:test';import assert from'node:assert/strict';
import{setBaseAllowance,readStorage}from'../../src/lib/storage/quota.mjs';import{storageRoutes}from'../../src/lib/storage/http.mjs';import{database,key}from'./database.mjs';import{identities}from'./identities.mjs';
test('admin overrides are audited and preserve active purchased capacity',async()=>{const d=await database();try{await identities(d.pool);await readStorage(d.pool,key);
await d.pool.query("INSERT INTO storage_entitlements VALUES('00000000-0000-4000-8000-000000000010',$1,$2,1000000000,now()-interval '1 hour',now()+interval '1 day','active','synthetic-purchase')",[key.tenantId,key.userId]);
await assert.rejects(setBaseAllowance(d.pool,{actor:{kind:'member',id:key.userId},key,baseBytes:'1',reason:'self'}),e=>e.status===403);
const r=await setBaseAllowance(d.pool,{actor:{kind:'member',id:'admin'},key,baseBytes:'7000000000',reason:'Team allocation'});assert.equal(r.effectiveBytes,'8000000000');
const audit=(await d.pool.query('SELECT old_base_bytes::text,new_base_bytes::text,actor_id FROM storage_override_audit')).rows;assert.deepEqual(audit,[{old_base_bytes:'5000000000',new_base_bytes:'7000000000',actor_id:'admin'}]);
await assert.rejects(setBaseAllowance(d.pool,{actor:{kind:'member',id:'admin'},key,baseBytes:'0',reason:'   '}));assert.equal((await readStorage(d.pool,key)).baseBytes,'7000000000');
}finally{await d.close();}});
test('HTTP endpoints reject CSRF, client actors, forged internal callers and cross-organization edits',async()=>{const d=await database();try{await identities(d.pool);
const handlers=storageRoutes({pool:d.pool,getActor:async()=>({kind:'member',id:'admin'}),origins:['https://members.example'],verifyService:async(req)=>{if(req.headers.get('authorization')!=='Bearer verified-service')throw Error('Invalid service');}});
const request=(body,origin='https://members.example',authorization)=>new Request('https://members.example/api/storage/allowance',{method:'PATCH',headers:{'content-type':'application/json',...(origin?{origin}:{}),...(authorization?{authorization}:{})},body:JSON.stringify(body)});
const body={...key,baseBytes:'8000000000',reason:'Team allocation'};
assert.equal((await handlers.PATCH(request(body,null))).status,403);assert.equal((await handlers.PATCH(request({...body,actor:{kind:'webmaster',id:'spoof'}}))).status,400);
assert.equal((await handlers.PATCH(request({...body,tenantId:'00000000-0000-4000-8000-000000000002'}))).status,403);
assert.equal((await handlers.INTERNAL(request({...body,webmasterActorId:'owner'},null,'Bearer forged'))).status,403);
assert.equal((await handlers.PATCH(request(body))).status,200);
assert.equal((await handlers.INTERNAL(request({...body,webmasterActorId:'owner'},null,'Bearer verified-service'))).status,200);
assert.equal((await d.pool.query('SELECT count(*) FROM storage_override_audit')).rows[0].count,'2');
}finally{await d.close();}});
test('own usage and member listing expose admin controls only to authorized callers',async()=>{const d=await database();try{await identities(d.pool);
const member=storageRoutes({pool:d.pool,getActor:async()=>({kind:'member',id:key.userId}),origins:['https://members.example']});
const url='https://members.example/api/storage/allowance?tenantId='+key.tenantId;
const r=await member.GET(new Request(url));assert.equal(r.status,200);const value=await r.json();assert.equal(value.baseBytes,'5000000000');assert.equal(value.canAdminister,false);assert.equal(value.purchasesAvailable,false);
assert.equal((await member.MEMBERS(new Request(url))).status,403);
const admin=storageRoutes({pool:d.pool,getActor:async()=>({kind:'member',id:'admin'}),origins:['https://members.example']});const listed=await admin.MEMBERS(new Request(url));assert.equal(listed.status,200);assert.equal((await listed.json()).members.length,3);
}finally{await d.close();}});
