import Link from 'next/link';
import {headers} from 'next/headers';
function rows<T>(value:unknown):T[]{return (Array.isArray(value)?value:(value as {rows?:T[]}).rows??[]) as T[]}
import { sql } from 'drizzle-orm';
import { db } from '@/lib/db';
import { requireTenantAccess } from '@/lib/auth/tenant-context';
import { PulseFrame } from './pulse-frame';
const labels:Record<string,string>={app_created:'App added',collection_enabled:'Collection enabled',collection_paused:'Collection paused',goal_created:'Conversion goal added',funnel_created:'Funnel added',credential_created:'Server access created',credential_revoked:'Server access revoked'};
export default async function PulsePage({searchParams}:{searchParams:Promise<{q?:string;site?:string}>}){
 const {tenantId,userId}=await requireTenantAccess();const search=await searchParams;const q=(search.q||'').trim().slice(0,100);
 const access=await db.execute(sql`select m.id from tenant_memberships m join tenants t on t.id=m.tenant_id where m.tenant_id=${tenantId} and m.user_id=${userId} and m.deleted_at is null and t.deleted_at is null and t.status not in ('suspended','cancelled') limit 1`);
 const accessRows=rows<{id:string}>(access);if(!accessRows?.length)return <p>Your access to this organization has changed.</p>;
 let apps:Array<{public_id:string;name:string;environment:string;enabled:boolean}>=[],activity:Array<{kind:string;created_at:string}>=[];
 try{const [sites,recent]=await Promise.all([db.execute(sql`select public_id,name,environment,enabled from pulse_sites where tenant_id=${tenantId} order by created_at desc limit 100`),db.execute(sql`select kind,created_at from pulse_activity where tenant_id=${tenantId} order by created_at desc limit 6`)]);apps=rows<(typeof apps)[number]>(sites);activity=rows<(typeof activity)[number]>(recent);}catch{}
 const h=await headers();const host=h.get("x-forwarded-host")||h.get("host")||"";const origin=host.endsWith(".axxes.app")||host==="axxes.app"?"https://pulse.axxes.app":"https://pulse.axxes.club";
 const filtered=apps.filter(a=>a.name.toLowerCase().includes(q.toLowerCase()));const site=apps.find(a=>a.public_id===search.site&&a.enabled)?.public_id;
 return <div><div className='mb-6 flex flex-wrap items-center justify-between gap-4'><div><h1 className='text-2xl font-semibold'>Pulse analytics</h1><p className='text-muted-foreground'>Your apps, traffic, and conversions in this organization.</p></div><Link className='text-sm underline' href={`https://pulse.axxes.app/api/organization/open?tenant=${tenantId}`} target='_blank' rel='noopener noreferrer'>Open Pulse ↗</Link></div><details className='mb-5 rounded-md border p-4'><summary className='cursor-pointer font-medium'>{apps.length} {apps.length===1?'app':'apps'} in Pulse · find an app and view recent changes</summary><form className='mt-4 flex gap-2' action='/pulse'><input aria-label='Find an analytics app' className='min-w-0 flex-1 rounded border p-2' name='q' defaultValue={q} placeholder='Search your apps'/><button className='rounded border px-3'>Find app</button></form><ul className='my-4 space-y-2'>{filtered.map(app=><li key={app.public_id}><Link className='underline' href={`/pulse?site=${app.public_id}`}>{app.name} · {app.environment}{app.enabled?'':' · paused'}</Link></li>)}{!filtered.length&&<li>No matching apps. Open Pulse to connect your first app.</li>}</ul><h2 className='text-sm font-medium'>Recent changes</h2><ul className='mt-2 space-y-1 text-sm text-muted-foreground'>{activity.map((item,i)=><li key={i}>{labels[item.kind]||'App settings changed'} · {new Date(item.created_at).toLocaleDateString('en-US',{timeZone:'UTC'})}</li>)}{!activity.length&&<li>No changes yet.</li>}</ul></details><PulseFrame tenantId={tenantId} siteId={site} origin={origin}/></div>
}
