'use client';
import{useState}from'react';
import type{StorageSnapshot}from'../../lib/storage/types';
import{formatBytes,bytesToGigabytes,gigabytesToBytes}from'../../lib/storage/format.mjs';
export type StorageMember=StorageSnapshot&{userId:string;name:string;role:string};
export function MemberLimits({members,onSave,onInspect,nextCursor,onMore}:{members:StorageMember[];onSave:(userId:string,bytes:string,reason:string)=>Promise<void>;onInspect?:(userId:string)=>Promise<void>;nextCursor?:string|null;onMore?:()=>void}){
 const[editing,setEditing]=useState<StorageMember|null>(null),[gb,setGb]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const save=async(reset=false)=>{if(!editing)return;setBusy(true);setError('');try{await onSave(editing.userId,reset?'5000000000':gigabytesToBytes(gb),reason);setEditing(null);}catch(e){setError(e instanceof Error?e.message:'Could not save allowance.');}finally{setBusy(false);}};
 return <section className="space-y-4"><h2 className="text-lg font-semibold">Member allowances</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Member','Used','Base','Purchased extra','Total',''].map((label,i)=><th key={i} className="p-2">{label}</th>)}</tr></thead><tbody>{members.map(m=><tr key={m.userId} className="border-t"><td className="p-2">{m.name}<small className="block text-muted-foreground">{m.role}</small></td><td className="p-2">{formatBytes(m.usedBytes)}</td><td className="p-2">{formatBytes(m.baseBytes)}</td><td className="p-2">{formatBytes(m.paidBytes)}</td><td className="p-2">{formatBytes(m.effectiveBytes)}</td><td className="space-x-2 p-2"><button type="button" className="underline" onClick={()=>{setEditing(m);setGb(bytesToGigabytes(m.baseBytes));setReason('');setError('');}}>Set allowance</button>{onInspect&&<button type="button" className="underline" onClick={()=>{void onInspect(m.userId).catch(e=>setError(e instanceof Error?e.message:'Could not load history.'));}}>History</button>}</td></tr>)}</tbody></table></div>
 {!members.length&&<p>No active members.</p>}{nextCursor&&onMore&&<button type="button" className="rounded border px-3 py-2" onClick={onMore}>Load more members</button>}
 {editing&&<form aria-label="Edit storage allowance" className="space-y-3 rounded-lg border p-4" onSubmit={event=>{event.preventDefault();void save();}}><h3 className="font-medium">Allowance for {editing.name}</h3><label className="block">Base allowance (GB)<input required inputMode="decimal" className="ml-3 rounded border p-2" value={gb} onChange={event=>setGb(event.target.value)} disabled={busy}/></label><p>Purchased storage is added separately. Lowering the allowance won’t delete files.</p><label className="block">Reason<textarea required maxLength={1000} className="mt-1 block w-full rounded border p-2" value={reason} onChange={event=>setReason(event.target.value)} disabled={busy}/></label><div className="flex flex-wrap gap-3"><button className="rounded border px-3 py-2" disabled={busy||!reason.trim()} type="submit">{busy?'Saving…':'Save allowance'}</button><button type="button" className="rounded border px-3 py-2" disabled={busy||!reason.trim()} onClick={()=>void save(true)}>Reset base to 5 GB</button><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button></div></form>}
 {error&&<p role="alert">{error}</p>}
 </section>;
}
