'use client';
import{useCallback,useEffect,useState}from'react';
import type{StorageSnapshot}from'../../lib/storage/types';
import{UsageMeter}from'./usage-meter';import{MemberLimits,type StorageMember}from'./member-limits';
type Audit={actor_kind:string;actor_id:string;old_base_bytes:string;new_base_bytes:string;reason:string;created_at:string};
type Allowance=StorageSnapshot&{canAdminister:boolean;audit:Audit[];purchasesAvailable:boolean};
async function call<T>(url:string,body?:unknown){const response=await fetch(url,{cache:'no-store',credentials:'same-origin',...(body?{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(data.error??'Storage request failed.');return data as T;}
export function StoragePanel({tenantId:initial,organizations=[]}:{tenantId:string;organizations?:{id:string;name:string}[]}){
 const [tenantId,setTenantId]=useState(initial);
 return <div className="mx-auto max-w-5xl space-y-6 p-6"><header><h1 className="text-2xl font-semibold">Storage</h1><p className="text-muted-foreground">Your allowance applies separately in each organization.</p></header>{organizations.length>1&&<label>Organization <select className="rounded border p-2" value={tenantId} onChange={event=>setTenantId(event.target.value)}>{organizations.map(org=><option key={org.id} value={org.id}>{org.name}</option>)}</select></label>}<StoragePanelContents key={tenantId} tenantId={tenantId}/></div>;
}
function StoragePanelContents({tenantId}:{tenantId:string}){
 const[snapshot,setSnapshot]=useState<Allowance|null>(null),[members,setMembers]=useState<StorageMember[]>([]),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState(''),[upgrade,setUpgrade]=useState(false),[audit,setAudit]=useState<Audit[]|null>(null);
 const loadMembers=useCallback(async(next?:string)=>{const value=await call<{members:StorageMember[];nextCursor:string|null}>(`/api/storage/members?tenantId=${encodeURIComponent(tenantId)}${next?'&cursor='+next:''}`);setMembers(old=>next?[...old,...value.members]:value.members);setCursor(value.nextCursor);},[tenantId]);
 const refresh=useCallback(async()=>{try{const value=await call<Allowance>(`/api/storage/allowance?tenantId=${encodeURIComponent(tenantId)}`);setError('');setSnapshot(value);if(value.canAdminister)await loadMembers();else{setMembers([]);setCursor(null);}}catch(e){setSnapshot(null);setError(e instanceof Error?e.message:'Storage is unavailable.');}},[tenantId,loadMembers]);
 useEffect(()=>{let active=true;void call<Allowance>(`/api/storage/allowance?tenantId=${encodeURIComponent(tenantId)}`).then(async value=>{if(!active)return;setSnapshot(value);if(value.canAdminister){const result=await call<{members:StorageMember[];nextCursor:string|null}>(`/api/storage/members?tenantId=${encodeURIComponent(tenantId)}`);if(active){setMembers(result.members);setCursor(result.nextCursor);}}}).catch(e=>{if(active){setSnapshot(null);setError(e instanceof Error?e.message:'Storage is unavailable.');}});return()=>{active=false;};},[tenantId]);
 return <div className="space-y-6">
 {error&&<p role="alert">{error}</p>}{snapshot?<><UsageMeter snapshot={snapshot}/><div className="flex gap-3"><button type="button" className="rounded border px-4 py-2" onClick={()=>setUpgrade(!upgrade)}>Buy more storage</button><button type="button" onClick={()=>void refresh()}>Refresh usage</button></div>{upgrade&&<div role="status" className="rounded border p-4">Extra storage plans aren’t available yet. You can ask your organization admin to adjust your allowance.</div>}{snapshot.canAdminister&&<MemberLimits members={members} nextCursor={cursor} onMore={()=>void loadMembers(cursor??undefined).catch(e=>setError(e.message))} onSave={async(userId,baseBytes,reason)=>{await call(`/api/storage/allowance`,{tenantId,userId,baseBytes,reason});await refresh();}} onInspect={async userId=>{const value=await call<Allowance>(`/api/storage/allowance?tenantId=${encodeURIComponent(tenantId)}&userId=${encodeURIComponent(userId)}`);setAudit(value.audit);}}/>}{audit&&<section className="space-y-2"><h2 className="text-lg font-semibold">Allowance history</h2>{audit.length?audit.map((entry,i)=><p key={i}>{new Date(entry.created_at).toLocaleString()} · {entry.actor_kind} · {entry.reason}</p>):<p>No allowance changes recorded.</p>}</section>}</>:!error&&<p role="status">Loading storage…</p>}
 </div>;
}
export function StorageSummary({tenantId}:{tenantId:string}){return <StorageSummaryForTenant key={tenantId} tenantId={tenantId}/>;}
function StorageSummaryForTenant({tenantId}:{tenantId:string}){
 const[snapshot,setSnapshot]=useState<Allowance|null>(null);
 useEffect(()=>{let active=true;const refresh=()=>{void call<Allowance>(`/api/storage/allowance?tenantId=${encodeURIComponent(tenantId)}`).then(value=>{if(active)setSnapshot(value);}).catch(()=>{if(active)setSnapshot(null);});};refresh();const timer=setInterval(refresh,30000);window.addEventListener('axxes:storage-changed',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('axxes:storage-changed',refresh);};},[tenantId]);
 return <div className="space-y-2">{snapshot&&<UsageMeter snapshot={snapshot} compact/>}<a className="text-sm underline" href={`/storage?tenantId=${encodeURIComponent(tenantId)}`}>Storage &amp; allowances</a></div>;
}
