import {wrapAdmission} from '@/lib/security/admission-server';
import {createRemoteJWKSet,jwtVerify} from 'jose';
import {NextRequest,NextResponse} from 'next/server';
import {mailActor,mailConfig,privateError} from '@/lib/mail/server';
import {openMailPayload,sealMailSession} from '@/lib/mail/security';
export const runtime='nodejs';
async function GETHandler(request:NextRequest){const config=mailConfig(),actor=await mailActor();if(!actor)return privateError('Sign in required',401);const flow=openMailPayload(request.cookies.get('axxes_mail_flow')?.value||'',config.sessionKey),state=request.nextUrl.searchParams.get('state'),code=request.nextUrl.searchParams.get('code');if(!flow||flow.userId!==actor||flow.state!==state||!code||typeof flow.expiresAt!=='number'||flow.expiresAt<=Date.now()||typeof flow.verifier!=='string'||typeof flow.nonce!=='string')return privateError('Mail sign-in expired; start again',400);
 try{const response=await fetch(config.handshake+'/api/workspace-oidc/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:config.clientId,client_secret:config.clientSecret,redirect_uri:config.callback,code,code_verifier:flow.verifier}),cache:'no-store',redirect:'error',signal:AbortSignal.timeout(15000)});if(!response.ok)return privateError('Mail sign-in could not be completed',503);const tokens=await response.json();if(!/^[A-Za-z]{32}$/.test(tokens.access_token)||!Number.isFinite(Number(tokens.expires_in))||Number(tokens.expires_in)<=0)return privateError('Mail sign-in response is unavailable',503);
 const issuer=config.handshake+'/api/workspace-oidc';const identityToken=await jwtVerify(tokens.id_token,createRemoteJWKSet(new URL(issuer+'/jwks')),{issuer,audience:config.clientId,algorithms:['RS256']});if(identityToken.payload.sub!==actor||identityToken.payload.nonce!==flow.nonce)return privateError('Mail identity did not match your session',403);
 const userResponse=await fetch(config.handshake+'/api/workspace-oidc/userinfo',{headers:{authorization:'Bearer '+tokens.access_token},cache:'no-store',redirect:'error',signal:AbortSignal.timeout(10000)});if(!userResponse.ok)return privateError('Mail identity could not be verified',503);const identity=await userResponse.json();if(identity.sub!==actor)return privateError('Mail identity did not match your session',403);
 const lifetime=Math.min(Number(tokens.expires_in),3600),result=NextResponse.redirect(config.origin+'/mail');result.cookies.set('axxes_mail_session',sealMailSession({userId:actor,accessToken:tokens.access_token,expiresAt:Date.now()+lifetime*1000},config.sessionKey),{httpOnly:true,secure:new URL(config.origin).protocol==='https:',sameSite:'lax',path:'/api/workspace',maxAge:lifetime});result.cookies.set('axxes_mail_flow','',{httpOnly:true,secure:new URL(config.origin).protocol==='https:',sameSite:'lax',path:'/api/workspace/auth',maxAge:0});result.headers.set('cache-control','no-store');return result;
 }catch{return privateError('Mail sign-in service is temporarily unavailable',503);}
}

export const GET=wrapAdmission(GETHandler,'src/app/api/workspace/auth/callback/route.ts'+':GET',12000);
