'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
type Inventory={id:string;name:string;price:string;quantity?:number;quantity_total?:number;quantity_sold?:number;quantity_reserved?:number};
type Setup={policy:{enabled?:boolean;mode?:'test'|'live';taxBps?:number;pickup?:{instructions:string};shipping?:{flatCents:number;countries:string[]}};merchants:{mode:string;verified_at:string}[];tickets:Inventory[];products:Inventory[];variants:Inventory[];orders:{id:string;mode:string;state:string;amount:number;amount_refunded:number;customer_email:string}[]};
const endpoint='/api/v1/website/gangstarz/commerce';
async function call(body?:unknown){const response=await fetch(endpoint,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error??'Commerce request failed');return value;}
export default function CommercePage(){
 const [setup,setSetup]=useState<Setup|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{let current=true;call().then(value=>{if(current)setSetup(value);}).catch(error=>{if(current)setMessage(error.message);});return()=>{current=false;};},[revision]);
 async function submit(event:React.FormEvent<HTMLFormElement>,build:(data:FormData)=>unknown){event.preventDefault();const form=event.currentTarget;setBusy(true);setMessage('');try{await call(build(new FormData(form)));setMessage('Saved.');setRevision(value=>value+1);if(form.dataset.credentials)form.reset();}catch(error){setMessage(error instanceof Error?error.message:'Request failed');}finally{setBusy(false);}}
 if(!setup)return <main className="p-6"><h1>Gangstarz commerce</h1><p role="status">{message||'Loading authorized commerce settings…'}</p></main>;
 return <main className="p-6 space-y-8"><Link href="/website/gangstarz">Website editor</Link><h1 className="text-2xl font-bold">Gangstarz commerce</h1><p role="status">{message}</p>
 <section><h2 className="text-xl">Payment merchant</h2><p>Use an existing Gangstarz merchant key with payments and refunds access. The server verifies its workspace and mode before saving encrypted credentials.</p><p>Configured modes: {setup.merchants.map(item=>item.mode).join(', ')||'none'}. <a href="https://tollbooth.axxes.club">Manage payment merchant</a></p>
 <form data-credentials="true" onSubmit={event=>submit(event,data=>({action:'merchant',mode:data.get('mode'),apiKey:data.get('apiKey'),webhookSecret:data.get('webhookSecret')}))} className="space-x-2"><select name="mode"><option value="test">Test</option><option value="live">Live</option></select><input name="apiKey" type="password" autoComplete="off" placeholder="Merchant API key" required/><input name="webhookSecret" type="password" autoComplete="off" placeholder="Notification signing secret" required/><button disabled={busy}>Verify and save</button></form><p>Notification endpoint: https://members.axxes.club/api/v1/public/tenants/gangstarz/commerce/webhook</p></section>
 <section><h2 className="text-xl">Sales and fulfillment</h2><form key={`policy-${revision}`} onSubmit={event=>submit(event,data=>{const pickup=String(data.get('pickup')||'').trim(),countries=String(data.get('countries')||'').split(',').map(item=>item.trim().toUpperCase()).filter(Boolean);return{action:'policy',policy:{enabled:data.get('enabled')==='on',mode:data.get('mode'),taxBps:Number(data.get('taxBps')), ...(pickup?{pickup:{instructions:pickup}}:{}),...(countries.length?{shipping:{flatCents:Number(data.get('shippingCents')),countries}}:{})}};})} className="grid gap-2 max-w-xl"><label><input name="enabled" type="checkbox" defaultChecked={setup.policy.enabled}/> Enable native sales</label><label>Mode <select name="mode" defaultValue={setup.policy.mode??'test'}><option value="test">Test</option><option value="live">Live</option></select></label><label>Approved tax rate in basis points <input type="number" name="taxBps" min="0" max="10000" defaultValue={setup.policy.taxBps??0} required/></label><label>Pickup instructions <textarea name="pickup" defaultValue={setup.policy.pickup?.instructions}/></label><label>Shipping price in cents <input name="shippingCents" type="number" min="0" defaultValue={setup.policy.shipping?.flatCents??0}/></label><label>Shipping country codes, separated by commas <input name="countries" defaultValue={setup.policy.shipping?.countries.join(',')}/></label><button disabled={busy}>Save approved policy</button></form></section>
 <section><h2 className="text-xl">Existing inventory</h2>{(['ticket','product','variant'] as const).map(kind=><div key={kind}>{(kind==='ticket'?setup.tickets:kind==='product'?setup.products:setup.variants).map(item=><form key={`${item.id}-${revision}`} onSubmit={event=>submit(event,data=>({action:'inventory',kind,id:item.id,price:data.get('price'),quantity:Number(data.get('quantity'))}))} className="flex gap-2 py-2"><span>{kind}: {item.name}</span><label>Price <input name="price" defaultValue={item.price} required pattern="[0-9]+(\.[0-9]{1,2})?"/></label><label>{kind==='ticket'?'Total capacity':'Stock'} <input name="quantity" type="number" min={kind==='ticket'?(item.quantity_sold??0)+(item.quantity_reserved??0):0} defaultValue={item.quantity_total??item.quantity??0} required/></label><button disabled={busy}>Save</button></form>)}</div>)}</section>
 <section><h2 className="text-xl">Orders</h2>{setup.orders.map(order=><article key={order.id} className="border p-3 my-2"><p>{order.id} · {order.mode} · {order.state} · {order.customer_email}</p><p>{order.amount} cents; refunded {order.amount_refunded} cents</p><form onSubmit={event=>submit(event,data=>({action:'refund',id:order.id,amount:Number(data.get('amount')),key:String(data.get('key'))}))}><label>Refund cents <input name="amount" type="number" min="1" max={order.amount-order.amount_refunded} required/></label><input name="key" type="hidden" value={`refund-${order.id}-${order.amount_refunded}`}/><button disabled={busy}>Request refund</button></form><form onSubmit={event=>submit(event,()=>({action:'fulfill',id:order.id}))}><button disabled={busy}>Mark physical items fulfilled</button></form></article>)}<p>Only confirmed returns restore stock. A refund does not automatically restore physical inventory.</p><form onSubmit={event=>submit(event,data=>({action:'return',itemId:data.get('itemId'),quantity:Number(data.get('quantity')),key:data.get('key')}))}><input name="itemId" placeholder="Canonical order item ID" required/><input name="quantity" type="number" min="1" placeholder="Returned quantity" required/><input name="key" placeholder="Unique return reference" minLength={12} required/><button disabled={busy}>Record received return</button></form></section>
 <section><h2 className="text-xl">Ticket admission</h2><form onSubmit={event=>submit(event,data=>({action:'scan',ticketCode:data.get('ticketCode'),mode:data.get('mode')}))}><input name="ticketCode" placeholder="Ticket code" required/><select name="mode"><option value="live">Live event</option><option value="test">Test only</option></select><button disabled={busy}>Check in ticket</button></form></section>
 </main>;
}
